export const dashboardStats = [
  { key: 'availablePets', label: 'Available Pets', query: "SELECT COUNT(*)::int AS value FROM Pets WHERE adoption_status='Available'", accent: 'mint' },
  { key: 'adoptedPets', label: 'Adopted Pets', query: "SELECT COUNT(*)::int AS value FROM Pets WHERE adoption_status='Adopted'", accent: 'stone' },
  { key: 'pendingApps', label: 'Pending Apps', query: "SELECT COUNT(*)::int AS value FROM Adoption_Applications WHERE status='Pending'", accent: 'peach' },
  { key: 'adopters', label: 'Total Adopters', query: "SELECT COUNT(*)::int AS value FROM Adopters", accent: 'blue' },
  { key: 'appointments', label: 'Appointments', query: "SELECT COUNT(*)::int AS value FROM Appointments", accent: 'violet' },
  { key: 'medical', label: 'Medical Records', query: "SELECT COUNT(*)::int AS value FROM Medical_Records", accent: 'rose' },
  { key: 'staff', label: 'Staff Members', query: "SELECT COUNT(*)::int AS value FROM Staff", accent: 'mint' },
  { key: 'donations', label: 'Total Donations', query: "SELECT COALESCE(SUM(amount),0)::numeric AS value FROM Donation", accent: 'gold', money: true },
];

export const relationships = [
  ['HOUSES', 'Shelter → Pets', '1 : N', 'Regular relationship'],
  ['RECEIVES', 'Pets → Adoption_Applications', '1 : N', 'Identifying relationship'],
  ['SUBMITS', 'Adopters → Adoption_Applications', '1 : N', 'Total participation on adopters side'],
  ['SCHEDULES', 'Pets → Appointments', '1 : N', 'Weak entity relationship'],
  ['HANDLES', 'Pet_Care_Providers → Appointments', '1 : N', 'Regular relationship'],
  ['HAS', 'Pets → Medical_Records', '1 : N', 'Identifying relationship'],
  ['CREATES', 'Veterinarian → Medical_Records', '1 : N', 'Subclass relationship'],
  ['HAS (Ref)', 'Adopters → References_Table', '1 : N', 'Identifying weak entity'],
  ['CARES FOR', 'Staff ↔ Pets', 'M : N', 'Junction table Staff_Pet'],
  ['MAKES', 'Adopters → Donation', '1 : N', 'Regular relationship'],
  ['ENROLLS IN', 'Dog ↔ Training_Programs', 'M : N', 'Junction table Dog_Training'],
  ['Is-A (d)', 'Pets → Dog / Cat / Other_Animal', 'Disjoint', 'EER specialization'],
  ['Is-A (o)', 'Adopters → Individual / Organization', 'Overlapping', 'EER specialization'],
  ['Is-A (d)', 'Pet_Care_Providers → Veterinarian / Groomer', 'Disjoint', 'EER specialization'],
  ['Is-A (d)', 'Staff → Volunteer / Employee', 'Disjoint', 'EER specialization'],
];

export const viewsMeta = [
  {
    key: 'availablePets',
    title: 'Available_Pets',
    badge: 'Simple View',
    sql: `CREATE OR REPLACE VIEW Available_Pets AS
SELECT pet_id, name, breed, age, gender, adoption_status
FROM Pets
WHERE adoption_status = 'Available';`,
  },
  {
    key: 'pendingApplications',
    title: 'Pending_Applications_View',
    badge: '3-table join',
    sql: `CREATE OR REPLACE VIEW Pending_Applications_View AS
SELECT aa.application_id, aa.application_date, p.name AS pet_name, p.breed,
       ad.first_name || ' ' || ad.last_name AS adopter_name, ad.phone
FROM Adoption_Applications aa
JOIN Pets p ON aa.pet_id = p.pet_id
JOIN Adopters ad ON aa.adopter_id = ad.adopter_id
WHERE aa.status = 'Pending';`,
  },
  {
    key: 'appointmentHistory',
    title: 'Pet_Appointment_History',
    badge: '3-table join',
    sql: `CREATE OR REPLACE VIEW Pet_Appointment_History AS
SELECT p.name AS pet_name, p.breed, a.appointment_date, a.service_type,
       a.duration_mins, pcp.name AS provider_name, pcp.visiting_fee
FROM Appointments a
JOIN Pets p ON a.pet_id = p.pet_id
JOIN Pet_Care_Providers pcp ON a.provider_id = pcp.provider_id;`,
  },
];

export const triggerMeta = [
  {
    key: 'approvalStatus',
    name: 'trg_approval_status',
    fires: 'AFTER UPDATE on Adoption_Applications',
    behavior: "When status becomes 'Approved', the related pet is marked 'Adopted'.",
  },
  {
    key: 'checkPetStatus',
    name: 'trg_check_pet_status',
    fires: 'BEFORE INSERT on Appointments',
    behavior: "Blocks appointment creation for pets already marked 'Adopted'.",
  },
  {
    key: 'logApplication',
    name: 'trg_log_application',
    fires: 'AFTER INSERT on Adoption_Applications',
    behavior: 'Writes an audit row into Application_Audit.',
  },
];

export const entityGroups = {
  primary: ['pets', 'adopters', 'applications', 'appointments', 'providers', 'medical', 'staff', 'donations', 'training'],
  support: ['shelters', 'dogs', 'cats', 'other-animals', 'pet-photos', 'individuals', 'organizations', 'references', 'veterinarians', 'groomers', 'availability', 'volunteers', 'employees', 'staff-pet', 'dog-training', 'audit-log'],
};

export const entities = {
  pets: {
    key: 'pets',
    route: '/pets',
    title: 'Pets',
    subtitle: 'Main adoption catalogue. Includes shelter assignment and dog/cat/other subclass details.',
    icon: 'bi-paw',
    table: 'Pets',
    pk: ['pet_id'],
    mode: 'custom',
    relatedRoutes: [
      { label: 'Shelters', route: '/shelters' },
      { label: 'Pet Photos', route: '/pet-photos' },
      { label: 'Dog rows', route: '/dogs' },
      { label: 'Cat rows', route: '/cats' },
      { label: 'Other animals', route: '/other-animals' },
    ],
  },
  adopters: {
    key: 'adopters',
    route: '/adopters',
    title: 'Adopters',
    subtitle: 'Adopter records with overlapping Individual and Organization subclass assignment.',
    icon: 'bi-people',
    table: 'Adopters',
    pk: ['adopter_id'],
    mode: 'custom',
    relatedRoutes: [
      { label: 'References', route: '/references' },
      { label: 'Individuals', route: '/individuals' },
      { label: 'Organizations', route: '/organizations' },
    ],
  },
  applications: {
    key: 'applications',
    route: '/applications',
    title: 'Adoption Applications',
    subtitle: 'Weak entity linking adopters and pets. Trigger-driven approval and audit flow.',
    icon: 'bi-file-earmark-check',
    table: 'Adoption_Applications',
    pk: ['application_id'],
    mode: 'custom',
    note: "When status changes to Approved, PostgreSQL trigger trg_approval_status updates the pet's adoption_status automatically.",
    relatedRoutes: [{ label: 'Audit Log', route: '/audit-log' }],
  },
  appointments: {
    key: 'appointments',
    route: '/appointments',
    title: 'Appointments',
    subtitle: 'Weak entity between pets and providers. The trigger blocks appointments for adopted pets.',
    icon: 'bi-calendar-check',
    table: 'Appointments',
    pk: ['appointment_id'],
    mode: 'custom',
    note: "The BEFORE INSERT trigger trg_check_pet_status prevents appointments for pets whose adoption_status is 'Adopted'.",
  },
  providers: {
    key: 'providers',
    route: '/providers',
    title: 'Pet Care Providers',
    subtitle: 'Core provider table. Related veterinarian, groomer, and availability tables stay accessible here.',
    icon: 'bi-hospital',
    table: 'Pet_Care_Providers',
    pk: ['provider_id'],
    fields: [
      { name: 'provider_id', label: 'Provider ID', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'qualification', label: 'Qualification', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'visiting_fee', label: 'Visiting Fee', type: 'number' },
    ],
    relatedRoutes: [
      { label: 'Veterinarians', route: '/veterinarians' },
      { label: 'Groomers', route: '/groomers' },
      { label: 'Availability', route: '/availability' },
    ],
  },
  medical: {
    key: 'medical',
    route: '/medical',
    title: 'Medical Records',
    subtitle: 'Weak entity attached to pets and optionally tied to veterinarians.',
    icon: 'bi-clipboard2-pulse',
    table: 'Medical_Records',
    pk: ['record_id'],
    serialPk: true,
    fields: [
      { name: 'record_id', label: 'Record ID', type: 'number', readonly: true },
      { name: 'record_date', label: 'Record Date', type: 'date', required: true },
      { name: 'diagnosis', label: 'Diagnosis', type: 'textarea' },
      { name: 'treatment', label: 'Treatment', type: 'textarea' },
      { name: 'follow_up_date', label: 'Follow Up Date', type: 'date' },
      { name: 'cost', label: 'Cost', type: 'number' },
      { name: 'pet_id', label: 'Pet', type: 'select', required: true },
      { name: 'provider_id', label: 'Veterinarian', type: 'select' },
    ],
  },
  staff: {
    key: 'staff',
    route: '/staff',
    title: 'Staff',
    subtitle: 'Core staff table with related volunteer, employee, and Staff_Pet assignment rows.',
    icon: 'bi-person-badge',
    table: 'Staff',
    pk: ['staff_id'],
    fields: [
      { name: 'staff_id', label: 'Staff ID', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'shift', label: 'Shift', type: 'select', required: true, options: ['Morning', 'Evening', 'Night'] },
    ],
    relatedRoutes: [
      { label: 'Volunteers', route: '/volunteers' },
      { label: 'Employees', route: '/employees' },
      { label: 'Staff_Pet', route: '/staff-pet' },
    ],
  },
  donations: {
    key: 'donations',
    route: '/donations',
    title: 'Donations',
    subtitle: 'Donation records made by adopters.',
    icon: 'bi-cash-coin',
    table: 'Donation',
    pk: ['donation_id'],
    fields: [
      { name: 'donation_id', label: 'Donation ID', type: 'text', required: true },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'donation_date', label: 'Donation Date', type: 'date', required: true },
      { name: 'purpose', label: 'Purpose', type: 'text' },
      { name: 'payment_mode', label: 'Payment Mode', type: 'select', options: ['Cash', 'UPI', 'Bank Transfer', 'Cheque'] },
      { name: 'adopter_id', label: 'Adopter', type: 'select' },
    ],
  },
  training: {
    key: 'training',
    route: '/training',
    title: 'Training Programs',
    subtitle: 'Training program catalogue plus dog enrollment mapping.',
    icon: 'bi-trophy',
    table: 'Training_Programs',
    pk: ['program_id'],
    fields: [
      { name: 'program_id', label: 'Program ID', type: 'text', required: true },
      { name: 'program_name', label: 'Program Name', type: 'text', required: true },
      { name: 'duration_weeks', label: 'Duration (weeks)', type: 'number' },
      { name: 'trainer_name', label: 'Trainer Name', type: 'text' },
    ],
    relatedRoutes: [{ label: 'Dog_Training', route: '/dog-training' }],
  },
  shelters: {
    key: 'shelters',
    route: '/shelters',
    title: 'Shelters',
    subtitle: 'Independent shelter table used by pets.',
    icon: 'bi-house-heart',
    table: 'Shelter',
    pk: ['shelter_id'],
    fields: [
      { name: 'shelter_id', label: 'Shelter ID', type: 'text', required: true },
      { name: 'shelter_name', label: 'Shelter Name', type: 'text', required: true },
      { name: 'address', label: 'Address', type: 'text' },
      { name: 'capacity', label: 'Capacity', type: 'number' },
      { name: 'phone', label: 'Phone', type: 'text' },
    ],
  },
  dogs: {
    key: 'dogs',
    route: '/dogs',
    title: 'Dog Subclass',
    subtitle: 'Subclass rows for dogs.',
    icon: 'bi-emoji-smile',
    table: 'Dog',
    pk: ['pet_id'],
    fields: [
      { name: 'pet_id', label: 'Pet', type: 'select', required: true },
      { name: 'size', label: 'Size', type: 'select', options: ['Small', 'Medium', 'Large'] },
      { name: 'is_trained', label: 'Is Trained', type: 'checkbox' },
    ],
  },
  cats: {
    key: 'cats',
    route: '/cats',
    title: 'Cat Subclass',
    subtitle: 'Subclass rows for cats.',
    icon: 'bi-stars',
    table: 'Cat',
    pk: ['pet_id'],
    fields: [
      { name: 'pet_id', label: 'Pet', type: 'select', required: true },
      { name: 'is_indoor', label: 'Indoor', type: 'checkbox' },
      { name: 'fur_length', label: 'Fur Length', type: 'select', options: ['Short', 'Medium', 'Long'] },
    ],
  },
  'other-animals': {
    key: 'other-animals',
    route: '/other-animals',
    title: 'Other Animal Subclass',
    subtitle: 'Subclass rows for non-dog and non-cat animals.',
    icon: 'bi-feather',
    table: 'Other_Animal',
    pk: ['pet_id'],
    fields: [
      { name: 'pet_id', label: 'Pet', type: 'select', required: true },
      { name: 'species_name', label: 'Species Name', type: 'text', required: true },
    ],
  },
  'pet-photos': {
    key: 'pet-photos',
    route: '/pet-photos',
    title: 'Pet Photos',
    subtitle: 'Multi-valued photo table for pets.',
    icon: 'bi-image',
    table: 'Pet_Photos',
    pk: ['photo_id'],
    serialPk: true,
    fields: [
      { name: 'photo_id', label: 'Photo ID', type: 'number', readonly: true },
      { name: 'pet_id', label: 'Pet', type: 'select', required: true },
      { name: 'photo_url', label: 'Photo URL', type: 'text', required: true },
    ],
  },
  individuals: {
    key: 'individuals',
    route: '/individuals',
    title: 'Individual Subclass',
    subtitle: 'Overlapping adopter subclass for individual adopters.',
    icon: 'bi-person',
    table: 'Individual',
    pk: ['adopter_id'],
    fields: [
      { name: 'adopter_id', label: 'Adopter', type: 'select', required: true },
      { name: 'occupation', label: 'Occupation', type: 'text' },
    ],
  },
  organizations: {
    key: 'organizations',
    route: '/organizations',
    title: 'Organization Subclass',
    subtitle: 'Overlapping adopter subclass for organizations.',
    icon: 'bi-buildings',
    table: 'Organization',
    pk: ['adopter_id'],
    fields: [
      { name: 'adopter_id', label: 'Adopter', type: 'select', required: true },
      { name: 'org_reg_no', label: 'Registration Number', type: 'text', required: true },
    ],
  },
  references: {
    key: 'references',
    route: '/references',
    title: 'References Table',
    subtitle: 'Weak entity for adopter references.',
    icon: 'bi-journal-text',
    table: 'References_Table',
    pk: ['ref_id'],
    serialPk: true,
    fields: [
      { name: 'ref_id', label: 'Reference ID', type: 'number', readonly: true },
      { name: 'adopter_id', label: 'Adopter', type: 'select', required: true },
      { name: 'ref_name', label: 'Reference Name', type: 'text', required: true },
      { name: 'ref_phone', label: 'Reference Phone', type: 'text', required: true },
    ],
  },
  veterinarians: {
    key: 'veterinarians',
    route: '/veterinarians',
    title: 'Veterinarian Subclass',
    subtitle: 'Disjoint provider subclass for veterinarians.',
    icon: 'bi-heart-pulse',
    table: 'Veterinarian',
    pk: ['provider_id'],
    fields: [
      { name: 'provider_id', label: 'Provider', type: 'select', required: true },
      { name: 'vet_license_no', label: 'License Number', type: 'text', required: true },
      { name: 'specialization', label: 'Specialization', type: 'text' },
    ],
  },
  groomers: {
    key: 'groomers',
    route: '/groomers',
    title: 'Groomer Subclass',
    subtitle: 'Disjoint provider subclass for groomers.',
    icon: 'bi-scissors',
    table: 'Groomer',
    pk: ['provider_id'],
    fields: [
      { name: 'provider_id', label: 'Provider', type: 'select', required: true },
      { name: 'tools_used', label: 'Tools Used', type: 'text' },
      { name: 'grooming_styles', label: 'Grooming Styles', type: 'text' },
    ],
  },
  availability: {
    key: 'availability',
    route: '/availability',
    title: 'Provider Availability',
    subtitle: 'Multi-valued provider availability table.',
    icon: 'bi-calendar-week',
    table: 'Provider_Availability',
    pk: ['avail_id'],
    serialPk: true,
    fields: [
      { name: 'avail_id', label: 'Availability ID', type: 'number', readonly: true },
      { name: 'provider_id', label: 'Provider', type: 'select', required: true },
      { name: 'day_of_week', label: 'Day of Week', type: 'select', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] },
    ],
  },
  volunteers: {
    key: 'volunteers',
    route: '/volunteers',
    title: 'Volunteer Subclass',
    subtitle: 'Disjoint staff subclass for volunteers.',
    icon: 'bi-person-heart',
    table: 'Volunteer',
    pk: ['staff_id'],
    fields: [
      { name: 'staff_id', label: 'Staff', type: 'select', required: true },
      { name: 'hours_per_week', label: 'Hours per Week', type: 'number' },
    ],
  },
  employees: {
    key: 'employees',
    route: '/employees',
    title: 'Employee Subclass',
    subtitle: 'Disjoint staff subclass for employees.',
    icon: 'bi-briefcase',
    table: 'Employee',
    pk: ['staff_id'],
    fields: [
      { name: 'staff_id', label: 'Staff', type: 'select', required: true },
      { name: 'salary', label: 'Salary', type: 'number' },
      { name: 'emp_id', label: 'Employee Code', type: 'text' },
    ],
  },
  'staff-pet': {
    key: 'staff-pet',
    route: '/staff-pet',
    title: 'Staff_Pet Junction',
    subtitle: 'Many-to-many assignment table between staff and pets.',
    icon: 'bi-diagram-3',
    table: 'Staff_Pet',
    pk: ['staff_id', 'pet_id'],
    fields: [
      { name: 'staff_id', label: 'Staff', type: 'select', required: true },
      { name: 'pet_id', label: 'Pet', type: 'select', required: true },
    ],
  },
  'dog-training': {
    key: 'dog-training',
    route: '/dog-training',
    title: 'Dog_Training Junction',
    subtitle: 'Many-to-many enrollment table between dogs and training programs.',
    icon: 'bi-award',
    table: 'Dog_Training',
    pk: ['pet_id', 'program_id'],
    fields: [
      { name: 'pet_id', label: 'Dog', type: 'select', required: true },
      { name: 'program_id', label: 'Program', type: 'select', required: true },
    ],
  },
  'audit-log': {
    key: 'audit-log',
    route: '/audit-log',
    title: 'Application Audit',
    subtitle: 'Trigger-generated audit rows for application inserts.',
    icon: 'bi-journal-check',
    table: 'Application_Audit',
    pk: ['audit_id'],
    serialPk: true,
    fields: [
      { name: 'audit_id', label: 'Audit ID', type: 'number', readonly: true },
      { name: 'application_id', label: 'Application ID', type: 'text' },
      { name: 'adopter_id', label: 'Adopter ID', type: 'text' },
      { name: 'pet_id', label: 'Pet ID', type: 'text' },
      { name: 'logged_at', label: 'Logged At', type: 'text' },
      { name: 'action_type', label: 'Action Type', type: 'text' },
    ],
  },
};

export const entityList = Object.values(entities);
